### ISSUE TITLE
License

### ISSUE THREAD

**Issue by justjosias** [Ptival/yugioh#1]
Since this is GPL, do you mean to require every game based on your tutorial to also be GPL-licensed?

**Comment by Ptival** [comment]
If you mean inspired by the code, not at all, I don't plan on enforcing anything on that front.

If you mean a game using a decent chunk of code that is directly grabbed from this repository, then I guess it should be GPL-licensed yeah, though in all honesty, in the current state of the code, there's not much to build on top of! :-) 

I did not expect someone to want to derive from this code base in its current state, I mostly don't want someone to make closed-source commercial work out of this.

**Comment by justjosias** [comment]
Okay. I am making an online Apples to Apples clone in Haskell, and using your tutorial as one of my resources to do so (I am a beginner at Haskell). I brought this up because I am licensing it under the BSD-3-Clause license and was wondering about potential conflicts there.

Thanks for the clarification.
